### ISSUE TITLE
Bug no hover dos botão icons

### ISSUE THREAD

**Issue by PauloTIgit** [Fabiorocharb/Portifolio#1]
# Bug botão icons

![image](https://github.com/Fabiorocharb/Portifolio/assets/92067743/9b0aa5e1-5798-4d80-b5e5-73f74aceafda)

**Solução**
adicionando o style background: transparent na linha 99 ````.icon i {```` o bug será resolvido.

![image](https://github.com/Fabiorocharb/Portifolio/assets/92067743/f4a0046d-c4ba-4845-8459-d781a977df95)

**Comment by Fabiorocharb** [comment]
Show meu querido !
Muito obrigado , porém era provisório até fazer o site , e o site ficou
concluído e não tirei ele do ar .

Mas mesmo assim agradeço a atenção

Em sex, 24 de mai de 2024 10:44, Paulo Fernando Ferreira Pires <
***@***.***> escreveu:
